# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [1]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0,1,0,1]]).T

In [2]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
# define syn1
syn1 = 2*np.random.random((1,4)) - 1
iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）



In [4]:
l1.shapex

(4, 1)

神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [7]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    print("Output After Training:")
    print(l2)
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l2_error = y - l2
    l2_delta = l2_error * nonlin(l2,True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error*nonlin(l1,True)
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1

    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    syn1 += np.dot(l1.T,l2_delta)
     # syn1 update weights
    

print("\n\n")
print(l2)

Output After Training:
[[0.00402118 0.004021   0.00402093 0.00402105]
 [0.49998546 0.49998545 0.49998545 0.49998545]
 [0.0038868  0.00388662 0.00388656 0.00388667]
 [0.49998448 0.49998448 0.49998447 0.49998448]]
Output After Training:
[[0.00402108 0.0040209  0.00402083 0.00402094]
 [0.49998546 0.49998546 0.49998546 0.49998546]
 [0.0038867  0.00388652 0.00388646 0.00388657]
 [0.49998448 0.49998448 0.49998448 0.49998448]]
Output After Training:
[[0.00402097 0.00402079 0.00402072 0.00402084]
 [0.49998546 0.49998546 0.49998546 0.49998546]
 [0.0038866  0.00388642 0.00388636 0.00388647]
 [0.49998448 0.49998448 0.49998448 0.49998448]]
Output After Training:
[[0.00402087 0.00402069 0.00402062 0.00402074]
 [0.49998546 0.49998546 0.49998546 0.49998546]
 [0.0038865  0.00388632 0.00388626 0.00388637]
 [0.49998448 0.49998448 0.49998448 0.49998448]]
Output After Training:
[[0.00402076 0.00402058 0.00402051 0.00402063]
 [0.49998546 0.49998546 0.49998546 0.49998546]
 [0.0038864  0.00388622 0.00388616 

 [0.49998484 0.49998484 0.49998484 0.49998484]]
Output After Training:
[[0.00397321 0.00397304 0.00397297 0.00397308]
 [0.49998579 0.49998579 0.49998579 0.49998579]
 [0.00384076 0.00384059 0.00384053 0.00384064]
 [0.49998484 0.49998484 0.49998484 0.49998484]]
Output After Training:
[[0.00397311 0.00397294 0.00397287 0.00397298]
 [0.49998579 0.49998579 0.49998579 0.49998579]
 [0.00384067 0.0038405  0.00384043 0.00384054]
 [0.49998484 0.49998484 0.49998484 0.49998484]]
Output After Training:
[[0.00397301 0.00397284 0.00397277 0.00397288]
 [0.49998579 0.49998579 0.49998579 0.49998579]
 [0.00384057 0.0038404  0.00384033 0.00384044]
 [0.49998484 0.49998484 0.49998484 0.49998484]]
Output After Training:
[[0.00397291 0.00397274 0.00397267 0.00397278]
 [0.4999858  0.4999858  0.4999858  0.4999858 ]
 [0.00384047 0.0038403  0.00384024 0.00384035]
 [0.49998484 0.49998484 0.49998484 0.49998484]]
Output After Training:
[[0.00397281 0.00397263 0.00397257 0.00397268]
 [0.4999858  0.4999858  0.4999858 

Output After Training:
[[0.00393078 0.00393061 0.00393055 0.00393066]
 [0.49998609 0.49998609 0.49998609 0.49998609]
 [0.00380004 0.00379987 0.00379981 0.00379992]
 [0.49998516 0.49998516 0.49998516 0.49998516]]
Output After Training:
[[0.00393068 0.00393051 0.00393045 0.00393056]
 [0.49998609 0.49998609 0.49998609 0.49998609]
 [0.00379994 0.00379978 0.00379972 0.00379982]
 [0.49998516 0.49998516 0.49998516 0.49998516]]
Output After Training:
[[0.00393059 0.00393042 0.00393035 0.00393046]
 [0.49998609 0.49998609 0.49998609 0.49998609]
 [0.00379985 0.00379969 0.00379962 0.00379973]
 [0.49998516 0.49998516 0.49998516 0.49998516]]
Output After Training:
[[0.00393049 0.00393032 0.00393026 0.00393037]
 [0.49998609 0.49998609 0.49998609 0.49998609]
 [0.00379976 0.00379959 0.00379953 0.00379964]
 [0.49998516 0.49998516 0.49998516 0.49998516]]
Output After Training:
[[0.00393039 0.00393022 0.00393016 0.00393027]
 [0.49998609 0.49998609 0.49998609 0.49998609]
 [0.00379966 0.0037995  0.00379944 

Output After Training:
[[0.00388881 0.00388865 0.00388859 0.00388869]
 [0.49998638 0.49998638 0.49998638 0.49998638]
 [0.00375975 0.00375959 0.00375953 0.00375963]
 [0.49998547 0.49998547 0.49998547 0.49998547]]
Output After Training:
[[0.00388872 0.00388856 0.00388849 0.0038886 ]
 [0.49998638 0.49998638 0.49998638 0.49998638]
 [0.00375966 0.0037595  0.00375944 0.00375954]
 [0.49998547 0.49998547 0.49998547 0.49998547]]
Output After Training:
[[0.00388862 0.00388846 0.0038884  0.0038885 ]
 [0.49998638 0.49998638 0.49998638 0.49998638]
 [0.00375957 0.00375941 0.00375935 0.00375945]
 [0.49998547 0.49998547 0.49998547 0.49998547]]
Output After Training:
[[0.00388853 0.00388837 0.0038883  0.00388841]
 [0.49998638 0.49998638 0.49998638 0.49998638]
 [0.00375948 0.00375932 0.00375926 0.00375936]
 [0.49998547 0.49998547 0.49998547 0.49998547]]
Output After Training:
[[0.00388844 0.00388827 0.00388821 0.00388832]
 [0.49998638 0.49998638 0.49998638 0.49998638]
 [0.00375939 0.00375923 0.00375917 

Output After Training:
[[0.00385107 0.00385091 0.00385085 0.00385095]
 [0.49998664 0.49998664 0.49998664 0.49998664]
 [0.00372351 0.00372336 0.0037233  0.0037234 ]
 [0.49998575 0.49998575 0.49998575 0.49998575]]
Output After Training:
[[0.00385098 0.00385082 0.00385076 0.00385086]
 [0.49998664 0.49998664 0.49998664 0.49998664]
 [0.00372343 0.00372327 0.00372321 0.00372331]
 [0.49998575 0.49998575 0.49998575 0.49998575]]
Output After Training:
[[0.00385089 0.00385073 0.00385067 0.00385077]
 [0.49998664 0.49998664 0.49998664 0.49998664]
 [0.00372334 0.00372318 0.00372312 0.00372323]
 [0.49998575 0.49998575 0.49998575 0.49998575]]
Output After Training:
[[0.0038508  0.00385064 0.00385058 0.00385068]
 [0.49998664 0.49998664 0.49998664 0.49998664]
 [0.00372325 0.0037231  0.00372304 0.00372314]
 [0.49998575 0.49998575 0.49998575 0.49998575]]
Output After Training:
[[0.0038507  0.00385055 0.00385048 0.00385059]
 [0.49998664 0.49998664 0.49998664 0.49998664]
 [0.00372316 0.00372301 0.00372295 

Output After Training:
[[0.00381181 0.00381166 0.0038116  0.0038117 ]
 [0.4999869  0.4999869  0.4999869  0.4999869 ]
 [0.00368582 0.00368567 0.00368561 0.00368571]
 [0.49998603 0.49998603 0.49998603 0.49998603]]
Output After Training:
[[0.00381172 0.00381157 0.00381151 0.00381161]
 [0.4999869  0.4999869  0.4999869  0.4999869 ]
 [0.00368573 0.00368558 0.00368552 0.00368562]
 [0.49998603 0.49998603 0.49998603 0.49998603]]
Output After Training:
[[0.00381163 0.00381148 0.00381142 0.00381152]
 [0.4999869  0.4999869  0.4999869  0.4999869 ]
 [0.00368565 0.0036855  0.00368544 0.00368554]
 [0.49998603 0.49998603 0.49998603 0.49998603]]
Output After Training:
[[0.00381154 0.00381139 0.00381133 0.00381143]
 [0.49998691 0.49998691 0.49998691 0.49998691]
 [0.00368556 0.00368541 0.00368535 0.00368545]
 [0.49998603 0.49998603 0.49998603 0.49998603]]
Output After Training:
[[0.00381145 0.0038113  0.00381124 0.00381134]
 [0.49998691 0.49998691 0.49998691 0.49998691]
 [0.00368548 0.00368533 0.00368527 

Output After Training:
[[0.00377474 0.00377459 0.00377454 0.00377463]
 [0.49998715 0.49998715 0.49998715 0.49998715]
 [0.00365022 0.00365008 0.00365002 0.00365012]
 [0.4999863  0.4999863  0.4999863  0.4999863 ]]
Output After Training:
[[0.00377466 0.00377451 0.00377445 0.00377455]
 [0.49998715 0.49998715 0.49998715 0.49998715]
 [0.00365014 0.00365    0.00364994 0.00365003]
 [0.4999863  0.4999863  0.4999863  0.4999863 ]]
Output After Training:
[[0.00377457 0.00377442 0.00377436 0.00377446]
 [0.49998715 0.49998715 0.49998715 0.49998715]
 [0.00365006 0.00364991 0.00364986 0.00364995]
 [0.4999863  0.4999863  0.4999863  0.4999863 ]]
Output After Training:
[[0.00377448 0.00377433 0.00377428 0.00377437]
 [0.49998715 0.49998715 0.49998715 0.49998715]
 [0.00364998 0.00364983 0.00364977 0.00364987]
 [0.4999863  0.4999863  0.4999863  0.4999863 ]]
Output After Training:
[[0.0037744  0.00377425 0.00377419 0.00377429]
 [0.49998715 0.49998715 0.49998715 0.49998715]
 [0.00364989 0.00364975 0.00364969 

Output After Training:
[[0.00374158 0.00374143 0.00374138 0.00374147]
 [0.49998737 0.49998737 0.49998737 0.49998737]
 [0.00361838 0.00361823 0.00361818 0.00361827]
 [0.49998654 0.49998654 0.49998654 0.49998654]]
Output After Training:
[[0.0037415  0.00374135 0.00374129 0.00374139]
 [0.49998737 0.49998737 0.49998737 0.49998737]
 [0.0036183  0.00361815 0.0036181  0.00361819]
 [0.49998654 0.49998654 0.49998654 0.49998654]]
Output After Training:
[[0.00374141 0.00374127 0.00374121 0.0037413 ]
 [0.49998737 0.49998737 0.49998737 0.49998737]
 [0.00361821 0.00361807 0.00361802 0.00361811]
 [0.49998654 0.49998654 0.49998654 0.49998654]]
Output After Training:
[[0.00374133 0.00374118 0.00374113 0.00374122]
 [0.49998737 0.49998737 0.49998737 0.49998737]
 [0.00361813 0.00361799 0.00361794 0.00361803]
 [0.49998654 0.49998654 0.49998654 0.49998654]]
Output After Training:
[[0.00374124 0.0037411  0.00374104 0.00374114]
 [0.49998738 0.49998738 0.49998738 0.49998738]
 [0.00361805 0.00361791 0.00361786 

 [0.4999868  0.4999868  0.4999868  0.4999868 ]]
Output After Training:
[[0.00370411 0.00370396 0.00370391 0.003704  ]
 [0.49998762 0.49998762 0.49998762 0.49998762]
 [0.00358238 0.00358225 0.00358219 0.00358228]
 [0.4999868  0.4999868  0.4999868  0.4999868 ]]
Output After Training:
[[0.00370402 0.00370388 0.00370383 0.00370392]
 [0.49998762 0.49998762 0.49998762 0.49998762]
 [0.00358231 0.00358217 0.00358211 0.0035822 ]
 [0.4999868  0.4999868  0.4999868  0.4999868 ]]
Output After Training:
[[0.00370394 0.0037038  0.00370375 0.00370384]
 [0.49998762 0.49998762 0.49998762 0.49998762]
 [0.00358223 0.00358209 0.00358204 0.00358213]
 [0.4999868  0.4999868  0.4999868  0.4999868 ]]
Output After Training:
[[0.00370386 0.00370372 0.00370366 0.00370376]
 [0.49998762 0.49998762 0.49998762 0.49998762]
 [0.00358215 0.00358201 0.00358196 0.00358205]
 [0.4999868  0.4999868  0.4999868  0.4999868 ]]
Output After Training:
[[0.00370378 0.00370364 0.00370358 0.00370368]
 [0.49998762 0.49998762 0.49998762

 [0.49998703 0.49998703 0.49998703 0.49998703]]
Output After Training:
[[0.00367082 0.00367068 0.00367063 0.00367072]
 [0.49998784 0.49998784 0.49998784 0.49998784]
 [0.00355041 0.00355028 0.00355022 0.00355031]
 [0.49998704 0.49998704 0.49998703 0.49998704]]
Output After Training:
[[0.00367074 0.0036706  0.00367055 0.00367064]
 [0.49998784 0.49998784 0.49998784 0.49998784]
 [0.00355033 0.0035502  0.00355015 0.00355023]
 [0.49998704 0.49998704 0.49998704 0.49998704]]
Output After Training:
[[0.00367066 0.00367052 0.00367047 0.00367056]
 [0.49998784 0.49998784 0.49998784 0.49998784]
 [0.00355026 0.00355012 0.00355007 0.00355016]
 [0.49998704 0.49998704 0.49998704 0.49998704]]
Output After Training:
[[0.00367058 0.00367044 0.00367039 0.00367048]
 [0.49998784 0.49998784 0.49998784 0.49998784]
 [0.00355018 0.00355005 0.00354999 0.00355008]
 [0.49998704 0.49998704 0.49998704 0.49998704]]
Output After Training:
[[0.0036705  0.00367036 0.00367031 0.0036704 ]
 [0.49998784 0.49998784 0.49998784

[[0.00363376 0.00363362 0.00363357 0.00363366]
 [0.49998808 0.49998808 0.49998808 0.49998808]
 [0.00351481 0.00351468 0.00351463 0.00351471]
 [0.49998729 0.49998729 0.49998729 0.49998729]]
Output After Training:
[[0.00363368 0.00363355 0.0036335  0.00363358]
 [0.49998808 0.49998808 0.49998808 0.49998808]
 [0.00351473 0.0035146  0.00351455 0.00351464]
 [0.49998729 0.49998729 0.49998729 0.49998729]]
Output After Training:
[[0.0036336  0.00363347 0.00363342 0.00363351]
 [0.49998808 0.49998808 0.49998808 0.49998808]
 [0.00351466 0.00351453 0.00351448 0.00351457]
 [0.49998729 0.49998729 0.49998729 0.49998729]]
Output After Training:
[[0.00363353 0.00363339 0.00363334 0.00363343]
 [0.49998808 0.49998808 0.49998808 0.49998808]
 [0.00351459 0.00351446 0.00351441 0.00351449]
 [0.49998729 0.49998729 0.49998729 0.49998729]]
Output After Training:
[[0.00363345 0.00363332 0.00363326 0.00363335]
 [0.49998808 0.49998808 0.49998808 0.49998808]
 [0.00351451 0.00351438 0.00351433 0.00351442]
 [0.4999872

 [0.49998754 0.49998754 0.49998754 0.49998754]]
Output After Training:
[[0.00359838 0.00359825 0.0035982  0.00359829]
 [0.4999883  0.4999883  0.4999883  0.4999883 ]
 [0.00348082 0.0034807  0.00348065 0.00348073]
 [0.49998754 0.49998754 0.49998754 0.49998754]]
Output After Training:
[[0.00359831 0.00359818 0.00359813 0.00359821]
 [0.49998831 0.49998831 0.4999883  0.49998831]
 [0.00348075 0.00348062 0.00348057 0.00348066]
 [0.49998754 0.49998754 0.49998754 0.49998754]]
Output After Training:
[[0.00359823 0.0035981  0.00359805 0.00359814]
 [0.49998831 0.49998831 0.49998831 0.49998831]
 [0.00348068 0.00348055 0.0034805  0.00348059]
 [0.49998754 0.49998754 0.49998754 0.49998754]]
Output After Training:
[[0.00359816 0.00359803 0.00359798 0.00359806]
 [0.49998831 0.49998831 0.49998831 0.49998831]
 [0.00348061 0.00348048 0.00348043 0.00348051]
 [0.49998754 0.49998754 0.49998754 0.49998754]]
Output After Training:
[[0.00359808 0.00359795 0.0035979  0.00359799]
 [0.49998831 0.49998831 0.49998831

 [0.49998777 0.49998777 0.49998777 0.49998777]]
Output After Training:
[[0.0035643  0.00356417 0.00356412 0.00356421]
 [0.49998852 0.49998852 0.49998852 0.49998852]
 [0.00344807 0.00344795 0.0034479  0.00344798]
 [0.49998777 0.49998777 0.49998777 0.49998777]]
Output After Training:
[[0.00356423 0.0035641  0.00356405 0.00356413]
 [0.49998852 0.49998852 0.49998852 0.49998852]
 [0.003448   0.00344788 0.00344783 0.00344791]
 [0.49998777 0.49998777 0.49998777 0.49998777]]
Output After Training:
[[0.00356415 0.00356403 0.00356398 0.00356406]
 [0.49998852 0.49998852 0.49998852 0.49998852]
 [0.00344793 0.00344781 0.00344776 0.00344784]
 [0.49998777 0.49998777 0.49998777 0.49998777]]
Output After Training:
[[0.00356408 0.00356395 0.0035639  0.00356399]
 [0.49998852 0.49998852 0.49998852 0.49998852]
 [0.00344786 0.00344774 0.00344769 0.00344777]
 [0.49998777 0.49998777 0.49998777 0.49998777]]
Output After Training:
[[0.00356401 0.00356388 0.00356383 0.00356391]
 [0.49998852 0.49998852 0.49998852

 [0.499988   0.499988   0.499988   0.499988  ]]
Output After Training:
[[0.00353044 0.00353032 0.00353027 0.00353035]
 [0.49998873 0.49998873 0.49998873 0.49998873]
 [0.00341554 0.00341542 0.00341537 0.00341545]
 [0.499988   0.499988   0.499988   0.499988  ]]
Output After Training:
[[0.00353037 0.00353025 0.0035302  0.00353028]
 [0.49998873 0.49998873 0.49998873 0.49998873]
 [0.00341547 0.00341535 0.0034153  0.00341538]
 [0.499988   0.499988   0.499988   0.499988  ]]
Output After Training:
[[0.0035303  0.00353018 0.00353013 0.00353021]
 [0.49998874 0.49998874 0.49998874 0.49998874]
 [0.0034154  0.00341528 0.00341524 0.00341531]
 [0.499988   0.499988   0.499988   0.499988  ]]
Output After Training:
[[0.00353023 0.0035301  0.00353006 0.00353014]
 [0.49998874 0.49998874 0.49998874 0.49998874]
 [0.00341533 0.00341521 0.00341517 0.00341525]
 [0.499988   0.499988   0.499988   0.499988  ]]
Output After Training:
[[0.00353016 0.00353003 0.00352999 0.00353007]
 [0.49998874 0.49998874 0.49998874

 [0.4999882  0.4999882  0.4999882  0.4999882 ]]
Output After Training:
[[0.00349938 0.00349926 0.00349921 0.00349929]
 [0.49998893 0.49998893 0.49998893 0.49998893]
 [0.00338569 0.00338557 0.00338553 0.0033856 ]
 [0.49998821 0.49998821 0.49998821 0.49998821]]
Output After Training:
[[0.00349931 0.00349919 0.00349914 0.00349922]
 [0.49998893 0.49998893 0.49998893 0.49998893]
 [0.00338562 0.0033855  0.00338546 0.00338554]
 [0.49998821 0.49998821 0.49998821 0.49998821]]
Output After Training:
[[0.00349924 0.00349912 0.00349907 0.00349915]
 [0.49998893 0.49998893 0.49998893 0.49998893]
 [0.00338555 0.00338544 0.00338539 0.00338547]
 [0.49998821 0.49998821 0.49998821 0.49998821]]
Output After Training:
[[0.00349917 0.00349905 0.00349901 0.00349908]
 [0.49998893 0.49998893 0.49998893 0.49998893]
 [0.00338549 0.00338537 0.00338533 0.0033854 ]
 [0.49998821 0.49998821 0.49998821 0.49998821]]
Output After Training:
[[0.0034991  0.00349898 0.00349894 0.00349901]
 [0.49998893 0.49998893 0.49998893

 [0.49998839 0.49998839 0.49998839 0.49998839]]
Output After Training:
[[0.00347167 0.00347155 0.00347151 0.00347159]
 [0.4999891  0.4999891  0.4999891  0.4999891 ]
 [0.00335906 0.00335894 0.0033589  0.00335897]
 [0.49998839 0.49998839 0.49998839 0.49998839]]
Output After Training:
[[0.0034716  0.00347149 0.00347144 0.00347152]
 [0.4999891  0.4999891  0.4999891  0.4999891 ]
 [0.00335899 0.00335888 0.00335883 0.00335891]
 [0.49998839 0.49998839 0.49998839 0.49998839]]
Output After Training:
[[0.00347154 0.00347142 0.00347137 0.00347145]
 [0.4999891  0.4999891  0.4999891  0.4999891 ]
 [0.00335893 0.00335881 0.00335877 0.00335884]
 [0.49998839 0.49998839 0.49998839 0.49998839]]
Output After Training:
[[0.00347147 0.00347135 0.00347131 0.00347138]
 [0.4999891  0.4999891  0.4999891  0.4999891 ]
 [0.00335886 0.00335875 0.00335871 0.00335878]
 [0.49998839 0.49998839 0.49998839 0.49998839]]
Output After Training:
[[0.0034714  0.00347128 0.00347124 0.00347132]
 [0.4999891  0.4999891  0.4999891 

 [0.49998858 0.49998858 0.49998858 0.49998858]]
Output After Training:
[[0.00344204 0.00344192 0.00344188 0.00344195]
 [0.49998928 0.49998928 0.49998928 0.49998928]
 [0.00333057 0.00333046 0.00333042 0.00333049]
 [0.49998858 0.49998858 0.49998858 0.49998858]]
Output After Training:
[[0.00344197 0.00344186 0.00344181 0.00344189]
 [0.49998928 0.49998928 0.49998928 0.49998928]
 [0.00333051 0.0033304  0.00333035 0.00333043]
 [0.49998859 0.49998858 0.49998858 0.49998858]]
Output After Training:
[[0.0034419  0.00344179 0.00344175 0.00344182]
 [0.49998928 0.49998928 0.49998928 0.49998928]
 [0.00333045 0.00333033 0.00333029 0.00333036]
 [0.49998859 0.49998859 0.49998859 0.49998859]]
Output After Training:
[[0.00344184 0.00344172 0.00344168 0.00344175]
 [0.49998928 0.49998928 0.49998928 0.49998928]
 [0.00333038 0.00333027 0.00333023 0.0033303 ]
 [0.49998859 0.49998859 0.49998859 0.49998859]]
Output After Training:
[[0.00344177 0.00344166 0.00344161 0.00344169]
 [0.49998928 0.49998928 0.49998928

 [0.49998879 0.49998879 0.49998879 0.49998879]]
Output After Training:
[[0.00341121 0.0034111  0.00341106 0.00341113]
 [0.49998947 0.49998947 0.49998947 0.49998947]
 [0.00330094 0.00330083 0.00330079 0.00330086]
 [0.49998879 0.49998879 0.49998879 0.49998879]]
Output After Training:
[[0.00341115 0.00341104 0.00341099 0.00341107]
 [0.49998947 0.49998947 0.49998947 0.49998947]
 [0.00330088 0.00330077 0.00330073 0.0033008 ]
 [0.49998879 0.49998879 0.49998879 0.49998879]]
Output After Training:
[[0.00341108 0.00341097 0.00341093 0.003411  ]
 [0.49998947 0.49998947 0.49998947 0.49998947]
 [0.00330082 0.00330071 0.00330067 0.00330074]
 [0.49998879 0.49998879 0.49998879 0.49998879]]
Output After Training:
[[0.00341102 0.00341091 0.00341087 0.00341094]
 [0.49998947 0.49998947 0.49998947 0.49998947]
 [0.00330076 0.00330065 0.00330061 0.00330068]
 [0.49998879 0.49998879 0.49998879 0.49998879]]
Output After Training:
[[0.00341096 0.00341085 0.0034108  0.00341088]
 [0.49998947 0.49998947 0.49998947

 [0.49998897 0.49998897 0.49998897 0.49998897]]
Output After Training:
[[0.00338344 0.00338333 0.00338329 0.00338336]
 [0.49998964 0.49998964 0.49998964 0.49998964]
 [0.00327424 0.00327414 0.0032741  0.00327417]
 [0.49998897 0.49998897 0.49998897 0.49998897]]
Output After Training:
[[0.00338338 0.00338327 0.00338323 0.0033833 ]
 [0.49998964 0.49998964 0.49998964 0.49998964]
 [0.00327418 0.00327408 0.00327404 0.00327411]
 [0.49998897 0.49998897 0.49998897 0.49998897]]
Output After Training:
[[0.00338331 0.00338321 0.00338316 0.00338323]
 [0.49998964 0.49998964 0.49998964 0.49998964]
 [0.00327412 0.00327402 0.00327398 0.00327405]
 [0.49998897 0.49998897 0.49998897 0.49998897]]
Output After Training:
[[0.00338325 0.00338314 0.0033831  0.00338317]
 [0.49998964 0.49998964 0.49998964 0.49998964]
 [0.00327406 0.00327396 0.00327392 0.00327399]
 [0.49998897 0.49998897 0.49998897 0.49998897]]
Output After Training:
[[0.00338319 0.00338308 0.00338304 0.00338311]
 [0.49998964 0.49998964 0.49998964

 [0.49998914 0.49998914 0.49998914 0.49998914]]
Output After Training:
[[0.00335651 0.0033564  0.00335636 0.00335643]
 [0.4999898  0.4999898  0.4999898  0.4999898 ]
 [0.00324835 0.00324825 0.00324821 0.00324827]
 [0.49998914 0.49998914 0.49998914 0.49998914]]
Output After Training:
[[0.00335645 0.00335634 0.0033563  0.00335637]
 [0.4999898  0.4999898  0.4999898  0.4999898 ]
 [0.00324829 0.00324819 0.00324815 0.00324822]
 [0.49998914 0.49998914 0.49998914 0.49998914]]
Output After Training:
[[0.00335639 0.00335628 0.00335624 0.00335631]
 [0.4999898  0.4999898  0.4999898  0.4999898 ]
 [0.00324823 0.00324813 0.00324809 0.00324816]
 [0.49998914 0.49998914 0.49998914 0.49998914]]
Output After Training:
[[0.00335632 0.00335622 0.00335618 0.00335625]
 [0.4999898  0.4999898  0.4999898  0.4999898 ]
 [0.00324817 0.00324807 0.00324803 0.0032481 ]
 [0.49998914 0.49998914 0.49998914 0.49998914]]
Output After Training:
[[0.00335626 0.00335616 0.00335612 0.00335619]
 [0.4999898  0.4999898  0.4999898 

 [0.49998932 0.49998932 0.49998932 0.49998932]]
Output After Training:
[[0.00332752 0.00332742 0.00332738 0.00332744]
 [0.49998997 0.49998997 0.49998997 0.49998997]
 [0.00322048 0.00322038 0.00322034 0.0032204 ]
 [0.49998932 0.49998932 0.49998932 0.49998932]]
Output After Training:
[[0.00332746 0.00332736 0.00332732 0.00332738]
 [0.49998997 0.49998997 0.49998997 0.49998997]
 [0.00322042 0.00322032 0.00322028 0.00322035]
 [0.49998932 0.49998932 0.49998932 0.49998932]]
Output After Training:
[[0.0033274  0.0033273  0.00332726 0.00332732]
 [0.49998997 0.49998997 0.49998997 0.49998997]
 [0.00322036 0.00322026 0.00322022 0.00322029]
 [0.49998932 0.49998932 0.49998932 0.49998932]]
Output After Training:
[[0.00332734 0.00332724 0.0033272  0.00332726]
 [0.49998997 0.49998997 0.49998997 0.49998997]
 [0.00322031 0.00322021 0.00322017 0.00322023]
 [0.49998932 0.49998932 0.49998932 0.49998932]]
Output After Training:
[[0.00332728 0.00332718 0.00332714 0.0033272 ]
 [0.49998997 0.49998997 0.49998997

 [0.49998951 0.49998951 0.49998951 0.49998951]]
Output After Training:
[[0.00329821 0.00329811 0.00329807 0.00329814]
 [0.49999014 0.49999014 0.49999014 0.49999014]
 [0.0031923  0.0031922  0.00319216 0.00319223]
 [0.49998951 0.49998951 0.49998951 0.49998951]]
Output After Training:
[[0.00329816 0.00329806 0.00329802 0.00329808]
 [0.49999014 0.49999014 0.49999014 0.49999014]
 [0.00319224 0.00319215 0.00319211 0.00319217]
 [0.49998951 0.49998951 0.49998951 0.49998951]]
Output After Training:
[[0.0032981  0.003298   0.00329796 0.00329802]
 [0.49999015 0.49999015 0.49999015 0.49999015]
 [0.00319219 0.00319209 0.00319205 0.00319212]
 [0.49998951 0.49998951 0.49998951 0.49998951]]
Output After Training:
[[0.00329804 0.00329794 0.0032979  0.00329797]
 [0.49999015 0.49999015 0.49999015 0.49999015]
 [0.00319213 0.00319203 0.003192   0.00319206]
 [0.49998951 0.49998951 0.49998951 0.49998951]]
Output After Training:
[[0.00329798 0.00329788 0.00329784 0.00329791]
 [0.49999015 0.49999015 0.49999015

[[0.00327045 0.00327035 0.00327031 0.00327038]
 [0.49999031 0.49999031 0.49999031 0.49999031]
 [0.0031656  0.0031655  0.00316547 0.00316553]
 [0.49998968 0.49998968 0.49998968 0.49998968]]
Output After Training:
[[0.00327039 0.0032703  0.00327026 0.00327032]
 [0.49999031 0.49999031 0.49999031 0.49999031]
 [0.00316555 0.00316545 0.00316541 0.00316548]
 [0.49998968 0.49998968 0.49998968 0.49998968]]
Output After Training:
[[0.00327034 0.00327024 0.0032702  0.00327027]
 [0.49999031 0.49999031 0.49999031 0.49999031]
 [0.00316549 0.0031654  0.00316536 0.00316542]
 [0.49998968 0.49998968 0.49998968 0.49998968]]
Output After Training:
[[0.00327028 0.00327018 0.00327014 0.00327021]
 [0.49999031 0.49999031 0.49999031 0.49999031]
 [0.00316544 0.00316534 0.0031653  0.00316537]
 [0.49998968 0.49998968 0.49998968 0.49998968]]
Output After Training:
[[0.00327022 0.00327013 0.00327009 0.00327015]
 [0.49999031 0.49999031 0.49999031 0.49999031]
 [0.00316538 0.00316529 0.00316525 0.00316531]
 [0.4999896